
export const CLEAN_STORE = 'CLEAN_STORE'

/**** AUTH EVENTS  ****/

// LOGIN EVENTS
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const CHECK_CONNECTED_REQUEST = 'CHECK_CONNECTED_REQUEST'
export const CHECK_CONNECTED_SUCCESS = 'CHECK_CONNECTED_SUCCESS'
export const CHECK_CONNECTED_FAILURE = 'CHECK_CONNECTED_FAILURE'

export const BECOME_STREAMER_REQUEST = 'BECOME_STREAMER_REQUEST'
export const BECOME_STREAMER_SUCCESS = 'BECOME_STREAMER_SUCCESS'
export const BECOME_STREAMER_FAILURE = 'BECOME_STREAMER_FAILURE'

// LOGOUT EVENTS
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const LOST_SESSION = 'LOST_SESSION'

/*--- END AUTH EVENTS  ---*/


/**** USER EVENTS  ****/

export const FILL_USER = 'FILL_USER'
export const FILL_CHANNEL = 'FILL_CHANNEL'
export const EMPTY_USER = 'EMPTY_USER'

/*--- END USER EVENTS  ---*/


/**** STREAM EVENTS  ****/

export const CREATE_STREAM_REQUEST = 'CREATE_STREAM_REQUEST'
export const CREATE_STREAM_SUCCESS = 'CREATE_STREAM_SUCCESS'
export const CREATE_STREAM_FAILURE = 'CREATE_STREAM_FAILURE'

export const GET_INFO_STREAM_REQUEST = 'GET_INFO_STREAM_REQUEST'
export const GET_INFO_STREAM_SUCCESS = 'GET_INFO_STREAM_SUCCESS'
export const GET_INFO_STREAM_FAILURE = 'GET_INFO_STREAM_FAILURE'

export const END_STREAM_REQUEST = 'END_STREAM_REQUEST'
export const END_STREAM_SUCCESS = 'END_STREAM_SUCCESS'
export const END_STREAM_FAILURE = 'END_STREAM_FAILURE'

export const UPLOAD_STREAM_REQUEST = 'UPLOAD_STREAM_REQUEST'
export const UPLOAD_STREAM_SUCCESS = 'UPLOAD_STREAM_SUCCESS'
export const UPLOAD_STREAM_FAILURE = 'UPLOAD_STREAM_FAILURE'

/*--- END STREAM EVENTS  ---*/


/**** VERSIONING EVENTS  ****/

export const SELECT_FILE = 'SELECT_FILE'
export const REMOVE_FILE = 'REMOVE_FILE'

export const START_WATCHING = 'START_WATCHING'
export const END_WATCHING = 'END_WATCHING'

export const DROPBOX_REQUEST = 'DROPBOX_REQUEST'
export const DROPBOX_SUCCESS = 'DROPBOX_SUCCESS'
export const DROPBOX_FAILURE = 'DROPBOX_FAILURE'

export const INIT_REQUEST = 'INIT_REQUEST'
export const INIT_SUCCESS = 'INIT_SUCCESS'
export const INIT_FAILURE = 'INIT_FAILURE'

export const SEND_VERSION_REQUEST = 'SEND_VERSION_REQUEST'
export const SEND_VERSION_SUCCESS = 'SEND_VERSION_SUCCESS'
export const SEND_VERSION_FAILURE = 'SEND_VERSION_FAILURE'

export const COMMIT_INFO_REQUEST = 'COMMIT_INFO_REQUEST'
export const COMMIT_INFO_SUCCESS = 'COMMIT_INFO_SUCCESS'
export const COMMIT_INFO_FAILURE = 'COMMIT_INFO_FAILURE'

export const GET_FILE_ID = 'GET_FILE_ID'

/*--- END VERSIONING EVENTS  ---*/


/**** NOTIFICATION EVENTS  ****/

export const SUB_CATEGORIES_REQUEST = 'SUB_CATEGORIES_REQUEST'
export const SUB_CATEGORIES_SUCCESS = 'SUB_CATEGORIES_SUCCESS'
export const SUB_CATEGORIES_FAILURE = 'SUB_CATEGORIES_FAILURE'

/*--- END NOTIFICATION EVENTS  ---*/

/**** NOTIFICATION EVENTS  ****/

export const ADD_NOTIF = 'ADD_NOTIF'
export const DEACTIVATE_NOTIF = 'DEACTIVATE_NOTIF'
export const DELETE_NOTIF = 'DELETE_NOTIF'

/*--- END NOTIFICATION EVENTS  ---*/